name: first workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "done"
      - name: print multi line
        run: |
            echo: "f1"
            echo: "f2"
